services:
  mysql:
    image: mysql:8.0
    container_name: qualify-guru-v2-mysql
    environment:
      - MYSQL_DATABASE=qualify_guru_v2
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=guru_user
      - MYSQL_PASSWORD=guru_secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: qualify-guru-v2-mongo
    environment:
      - MONGO_INITDB_DATABASE=qualify_guru_v2_docs
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mysql_data: