services:
  api:
    build: .
    image: qualify-guru-api
    container_name: qualify-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      minio:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - PROFILE=local
      - DATASOURCE_URL=${DATASOURCE_URL_PRD}
      - DATASOURCE_USER=${DATASOURCE_USER}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}

      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}

  mysql:
    image: mysql:8.0
    container_name: qualify-guru-v2-mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATASOURCE_USER}
      - MYSQL_PASSWORD=${DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
      start_period: 10s

  minio:
    image: minio/minio:latest
    container_name: qualify-minio
    restart: always
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console UI
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=qualify-guru-resumes
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql_data:
  minio_data: